fix: Register validator callbacks on p2p client before starting (#17230)
Second attempt at
https://github.com/AztecProtocol/aztec-packages/pull/17207

The issue was that the `start` method on p2p client would overwrite all
previously registered subprotocol handlers, hence the errors we were
seeing on CI:
```
22:00:04 [22:00:04.697] WARN: p2p:4506:libp2p_service:4506:libp2p_service:4506:reqresp:4506 Unknown stream error while handling the stream, aborting {"protocol":"/aztec/req/auth/1.0.0"}
22:00:04     err: {
22:00:04       "type": "TypeError",
22:00:04       "message": "handler is not a function",
22:00:04       "stack":
22:00:04           TypeError: handler is not a function
22:00:04               at /home/aztec-dev/aztec-packages/yarn-project/p2p/dest/services/reqresp/reqresp.js:452:40
22:00:04               at processTicksAndRejections (node:internal/process/task_queues:105:5)
22:00:04               at duplex.sink (/home/aztec-dev/aztec-packages/yarn-project/node_modules/it-byte-stream/src/index.ts:86:22)
22:00:04     }
```

The test was also failing locally (it had passed before I submitted due
to a build issue I missed), and since it was tagged as flake it was
greenlighted by CI on the PR.